version: '3'
services:

  green:
    container_name: green
    image: llimy1/nuwa
    ports:
      - "8081:8080"
    environment:
      MARIADB_URL: ${MARIADB_URL}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_NAME: ${MARIADB_NAME}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGODB_IP: ${MONGODB_IP}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INIT_ROOT_USERNAME: ${MONGO_INIT_ROOT_USERNAME}
      MONGO_INIT_ROOT_PASSWORD: ${MONGO_INIT_ROOT_PASSWORD}
      SENTRY_KEY: ${SENTRY_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_URI: ${GOOGLE_URI}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      NAVER_URI: ${NAVER_URI}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_URI: ${KAKAO_URI}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}

  blue:
    container_name: blue
    image: llimy1/nuwa
    ports:
      - "8082:8080"
    environment:
      MARIADB_URL: ${MARIADB_URL}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_NAME: ${MARIADB_NAME}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGODB_IP: ${MONGODB_IP}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INIT_ROOT_USERNAME: ${MONGO_INIT_ROOT_USERNAME}
      MONGO_INIT_ROOT_PASSWORD: ${MONGO_INIT_ROOT_PASSWORD}
      SENTRY_KEY: ${SENTRY_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_URI: ${GOOGLE_URI}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      NAVER_URI: ${NAVER_URI}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_URI: ${KAKAO_URI}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}

  redis:
    image: redis:alpine
    command: redis-server /usr/local/etc/nuwa-redis/redis.conf --requirepass ${REDIS_PASSWORD}
    container_name: nuwa-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/nuwa-redis:/data
      - ./data/nuwa-redis/redis.conf:/usr/local/etc/nuwa-redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  mongo:
    image: mongo
    container_name: nuwa-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/nuwa-mongo:/data
    environment:
      MONGODB_IP: ${MONGODB_IP}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGO_INIT_ROOT_USERNAME: ${MONGO_INIT_ROOT_USERNAME}
      MONGO_INIT_ROOT_PASSWORD: ${MONGO_INIT_ROOT_PASSWORD}
