spring:
  profiles:
    active: dev
    include:
      - db
      - sentry
      - jwt
      - oauth

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#    database-platform: org.hibernate.dialect.MariaDB106Dialect
#        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.sql: debug
