spring:
  datasource:
    hikari:
      max-lifetime: 177000 # 177초, hikari는 RDS wait_timeout(180초) 보다 2 ~ 3초 정도 짧게 줄 것을 권장

    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_URL}/${MARIADB_NAME}?characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false

#  datasource:
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_NAME}?characterEncoding=UTF-8&characterSetResults=UTF-8

  data:
    redis:
      host: ${REDIS_USERNAME}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://${MONGO_INIT_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGODB_IP}:${MONGODB_PORT}/${MONGODB_NAME}?authSource=admin&authMechanism=SCRAM-SHA-1