spring:
  profiles:
    active: dev
    include:
      - db
      - sentry
      - jwt
      - oauth
      - aws

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  #    database-platform: org.hibernate.dialect.MariaDB106Dialect
#        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#logging:
#  level:
#    org.hibernate.sql: debug
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE

  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
